export const ALGORITHM_START = 'ALGORITHM.START'
export const ALGORITHM_STEP = 'ALGORITHM.STEP'
export const ALGORITHM_RUN = 'ALGORITHM.RUN'

export const INSPECTOR_SHOW = 'INSPECTOR.SHOW'
export const INSPECTOR_CLEAR = 'INSPECTOR.CLEAR'
